### PR TITLE
Fix Bug #527 Closing MessageReciever does not cancel Recieve operation

### PR DESCRIPTION
**Pull request by JohnLTaylor**
[Fix Bug #527 Closing MessageReciever does not cancel Recieve operation](https://github.com/Azure/azure-service-bus-dotnet/issues/527).

OnCloseAsync will now wait for the MessageReceiverPump to terminate

### CODE REVIEW

**Comment by SeanFeldman** [comment]
> OnCloseAsync will now wait for the MessageReceiverPump to terminate

The issue #527 states in expected behaviour:

> Receive operation is cancelled and no exception is thrown

`Close` operation should not wait for `Recieve()` to timeout.  It should close receiver's connection and cancel `Recieve()`. Also, note that the issue was raised for raw receive operation, the abstraction on top of it (message pump with callback).

**Comment by JohnLTaylor** [comment]
There is a problem when the stateful service is changing from the active partition to non-active.  If the message pump task isn't complete before ClientEntity.CloseAsync completes any access to the reliable store will cause a FabricNotPrimaryException exception.

**Comment by SeanFeldman** [comment]
@JohnLTaylor yes, Service Fabric (SF) will move around your services (stateful or stateless), closing them in the process. But that's a symptom, not the actual problem. The underlying problem is that currently ASB client does not stop receive operation if one is in progress and client is closed.

**Comment by nemakam** [comment]
@JohnLTaylor 
This change might not be required. The aim is that `MessagePumpTaskAsync` gets out of loop when `CloseAsync()` is called. Most of the waiting methods have access to the `cancellationToken` and the `receiveAsync()` itself should ideally return the moment the connection is broken down.

**Comment by JohnLTaylor** [comment]
@nemakam Without changing the interface, this is not possible as the cancellation token is not passed to messageReceiver.ReceiveAsync.

**Comment by nemakam** [comment]
@JohnLTaylor Take a look at this discussion https://github.com/Azure/azure-service-bus-dotnet/issues/439#issuecomment-401473918.
Basically when you close the connection, all existing operations are expected to exit immediately. There are places when it doesn't. This is something that should be taken care by the underneath AMQP layer which manages all connections and messages through the networking channel. It will be fixed soon wihtout having to change the interface

**Comment by nemakam** [comment]
Closing this as it as already fixed.

**Pull request closed without merging**
