### PR TITLE
Adding AppVeyor CI

### PR DESCRIPTION
**Pull request by jtaubensee**
Currently fails when running the tests from PowerShell. Will investigate.
2016-12-20_14h58_52

### CODE REVIEW

**Comment by jtaubensee** [comment]
No longer receiving the above error.

**Comment by jtaubensee** [comment]
@SeanFeldman - Regarding the unit tests? Yes, unfortunately that is true. We will need to think about implementing a private build that can be run without risk of exposing the credentials.

**Comment by SeanFeldman** [comment]
Right. Reason I'm asking is that there's no way to know if PR is failing or
not and it would require manual verification on each PR.

**Comment by jtaubensee** [comment]
Yep, I totally agree. As we have more and more PR's my team and I will need to do this for efficiency purposes. Stay tuned...

**Pull request merged**
