### PR TITLE
XML doco

### PR DESCRIPTION
**Pull request by SeanFeldman**
Targets PR #481
Depends on #503 

@nemakam is the approach to take? I'm basing of documentation on the world client as there're no tests for all exceptions.

### CODE REVIEW

**Comment by nemakam** [comment]
The approach looks perfect. 👍  
Do you think its too much redundancy to mention same set of exceptions for each operation? Maybe we should just specify exceptions thrown in interface summary?

**Comment by SeanFeldman** [comment]
Right now my biggest issue is that I don't know what specific exception can be thrown on the backend for each operation. I'm feeding off the namespace manager documentation atm, which is not ideal. Any recommendaitons how to handle that?

**Comment by nemakam** [comment]
I look at it as all the exceptions thats been implemented in client and not in service. If client doesn't understand any exception, it anyway converts it into a generic `ServiceBusException`. So instead of focusing on server, how about just looking at client exception handler and document accordingly?
Checkout `ManagementClient.ValidateHttpResponse()` method. I think you already got almost everything right (with an exception of `QuotaExceededException`)

**Comment by SeanFeldman** [comment]
Ok. Then a proper review would need to be conducted when I'm done.
I'll also do it on the `ManagementClient` and not the contract `IManagementClient`.

**Comment by SeanFeldman** [comment]
@nemakam I'm going to pause this. Not sure how much of a value this is since you'll have to go over it and fix pretty much everything 🙁

**Comment by nemakam** [comment]
@SeanFeldman 
Okay, I' merging this and will continue from where you left.

**Comment by SeanFeldman** [comment]
Thanks @nemakam.

Probably would be good to align documentation with #67 (Path and Name confusion).

**Pull request merged**
