### PR TITLE
Clients can be created with connectionStringBuilder

### PR DESCRIPTION
**Pull request by nemakam**
## Description
Exposed additional constructors in clients which take ServiceBusConnectionStringBuilder instead of the connection strings.
Address #122 

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](./CONTRIBUTING.md).**
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR.
- [x] The pull request does not introduce breaking changes (unless a major version change occurs in the assembly and module).
- [x] If applicable, the public code is properly documented.
- [ ] Pull request includes test coverage for the included changes.
- [x] The code builds without any errors.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@nemakam Is this PR addressing issue #135 ?

**Comment by jtaubensee** [comment]
Addresses #135 and #122

**Comment by SeanFeldman** [comment]
Thank you @jtaubensee 

Would be good to add that info in the general description of PRs when those are created - helps to understand the context during review. Context is 👑, right? 😃

**Comment by nemakam** [comment]
@jtaubensee @SeanFeldman , this does not address #135 . It currently only addresses #122 .

**Comment by SeanFeldman** [comment]
Context **is** the 👑!

@nemakam gets the points for updating the context.
Next time will be a 🏅 to have that in the context of a newly created PR 😃

**Comment by jtaubensee** [comment]
@nemakam - Can you take a look at the merge conflicts?

**Pull request merged**
