### PR TITLE
Enabling source linking

### LINKED ISSUE #280: Add Source Link support
### Why?

To make developers life easier. Allow stepping into ASB client source code when needed w/o wasting time.

### How?

[SourceLink](https://github.com/ctaggart/SourceLink)

### Will it support multiple targets?

Yes

### What will it look like?

I've applied this to [`ServiceBus.AttachmentPlugin`](https://www.nuget.org/packages/servicebus.attachmentplugin) version 1.0.2 and up. You can try that in action or see this sample project using it:

sourcelinking

### PR DESCRIPTION
**Pull request by SeanFeldman**
## Description

Fixes #280 

<details>
<summary>This following list is used to make sure that common guidelines for a pull request are followed.</summary>

- **Read the [contribution guidelines](./CONTRIBUTING.md).** 
- Make title of the pull request clear and informative. 
- Link to appropriate [issue](https://github.com/Azure/azure-service-bus-dotnet/issues).
- Include test coverage for the changes.
</details>

### CODE REVIEW

**Comment by SeanFeldman** [comment]
To verify this is working, make sure source code for ASB client is not found of the machine or rename the folder with the source code path. 

1. Create a simple test project that uses ASB client.
1. Set a breakpoint and step in.
1. On the first step-in operation, a popup should appear requesting to download the source. 
1. Approve it. 

Successful step-in into ASB code is a proof of source linking working.

@vinaysurya @nemakam if you could please verify this is working, would be great. Please note you'd need to use artifact from a build server or force it. If you have a dotnet project, you can test locally with:
```
dotnet restore
dotnet build /p:ci=true /v:n
```
With an full framework project, you can test locally with:
```
msbuild /t:restore
msbuild /t:rebuild /p:ci=true /v:n
```

**Comment by vinaysurya** [comment]
Thanks for the PR @SeanFeldman!  It works. The  pdb's were packed into the nuget package and on installing the nuget, I was able to hit and enter the ASB sourecode correctly. 

I have a couple of questions :
1) Regarding this, so whenever we build and create nuget packages for release, we always do it with the /p and /v options set?
msbuild /t:rebuild /p:ci=true /v:n

2) For some reason, it was not able to continue debugging at certain points. For ex. It would hit the breakpoints for ThrowIfClosed, also hit further breakpoints to the property InnerSender and Get a Sender, but then never really enter the Sender.SendAsync() part of the code.. I tried the freeze other threads and continue debugging this thread only method but was not able to continue debugging into this part. Is there anything I'm missing here?

public Task SendAsync(IList<Message> messageList)
{
            this.ThrowIfClosed();
            return this.InnerSender.SendAsync(messageList);
 }

**Comment by SeanFeldman** [comment]
> so whenever we build and create nuget packages for release, we always do it with the /p and /v options set?

That was only required for local builds. SourceLink is smart enough to detect build server. Locally, where build server environment variables are missing, it requires a hint via MSBuild variable.



> For some reason, it was not able to continue debugging at certain points

In theory, just like with any PDB, if code is optimized when compiled in Release mode, there could be some issues. But I'm not an expert :) Could you share the project on GH and I'll try myself as well?

**Comment by vinaysurya** [comment]
@SeanFeldman, it does look like it has something to do with the code optimizations.. @nemakam and me tried packing in the debug build into the nuget just to try and with that we were able to trace all the code as expected. 

I was just trying the debug on a cloned samples project installing the locallycreated nuget? Would it help to share that still?

**Comment by SeanFeldman** [comment]
> I was just trying the debug on a cloned samples project installing the locallycreated nuget? Would it help to share that still?

Sorry, share what? A Debug pdb? Hmm, how that would help when the package contains a Release dll? Not sure 😕

**Comment by vinaysurya** [comment]
Oh no, what i meant was you had asked me to share my project on GH.. So I mentioned that the project I was using to debug was just our samples project and was asking if you still wanted me to share something from my side?

**Comment by SeanFeldman** [comment]
Gotta love async communication 😄
In that case all good. Another option is perhaps raise the issue with SourceLink to see if they could suggest something. If that's strictly Debug vs Release with optimizations issue, don't know [what else can be done](https://github.com/ctaggart/SourceLink/issues/227).

**Comment by vinaysurya** [comment]
@SeanFeldman, if it works sometimes and does not work with say Async methods or because of release optimization etc, I am not sure if we are able to make it any more easier to the user to debug issues? With that do you think it is still helpful to include this?

**Comment by SeanFeldman** [comment]
@vinaysurya it's not that it sometimes works and sometimes doesn't. It does what PDBs are supposed to do and it can't achieve it when code in Release is optimized. That's a limitation of the release compiled assemblies as far as I know.

Now does that mean that there's no value is source linking? I'd say no. It's much better to be able to step into the source code than not to be able to do so. Very few people set up properly Symbols server. And if they do, you would need to push PDBs to the server. And that will still not solve the Release mode optimizations 🙂 

So if you ask me wherever it's worth having this is or not, my personal preference would be to include it. We can't make it perfect, but we can make the experience much better than it is right now.

**Comment by SeanFeldman** [comment]
PS: ask yourself the following questions:

Anyone downloading ASB client today, can they step in? No.
With SourceLink-ing, will they be able? Yes.
Does it break anything we ship? No.

Can't find a good reason not to go with the idea.

**Comment by vinaysurya** [comment]
@SeanFeldman, Ack, we discussed this within team as well and agree that to the extent possible it makes sense to make it easy for the developer debug expereince. Thanks for the PR again!

**Pull request merged**
