### PR TITLE
API approver

### LINKED ISSUE #40: Public API validation
Related to #39 

Minimal public API surface area validation should be automated to ensure that no internal types leaked out.
Suggest we look into [API Approver](https://github.com/JakeGinnivan/ApiApprover) to control the public API surface area, when API Approver supports .NET Standard.

/cc @jtaubensee

### PR DESCRIPTION
**Pull request by SeanFeldman**
Fixes #40 
This PR allows better control over public API surface.
API approval keeps public API changes from creeping in when those should not be made.

## How does it work?

`ApiApprovals` class contains a test named `ApproveAzureServiceBus`. This test is responsible to perform **public** API surface scan and compare the result with an already approved API (stored in `ApiApprovals.ApproveAzureServiceBus.approved.txt` file that is checked in).

When no public API changes are detected, the test will be green. When a public API is detected, one of the two has to take place:

1. API change should **not** be public. Rectify the issue and re-run the test. If it's green, the issue was addressed properly and API is internalized.
1. API change should be public. The `ApiApprovals.ApproveAzureServiceBus.approved.txt` file needs to be updated with the contents of a temporary generated `ApiApprovals.ApproveAzureServiceBus.received.txt` (this file contains API with all the recent changes). By virtue of updating the `ApiApprovals.ApproveAzureServiceBus.approved.txt` file, API is _approved_.

Example of API change caught by the test:
image

<details>
<summary>Failing test error message</summary>
ApprovalTests.Core.Exceptions.ApprovalMismatchException : Failed Approval: Received file C:\github\SeanFeldman\azure-service-bus-dotnet\test\Microsoft.Azure.ServiceBus.UnitTests\API\ApiApprovals.ApproveAzureServiceBus.received.txt does not match approved file C:\github\SeanFeldman\azure-service-bus-dotnet\test\Microsoft.Azure.ServiceBus.UnitTests\API\ApiApprovals.ApproveAzureServiceBus.approved.txt.
   at ApprovalTests.Approvers.FileApprover.Fail()
   at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)
   at ApprovalTests.Approvals.Verify(IApprovalWriter writer)
   at ApprovalTests.Approvals.Verify(String text)
   at Microsoft.Azure.ServiceBus.UnitTests.API.ApiApprovals.ApproveAzureServiceBus() in C:\github\SeanFeldman\azure-service-bus-dotnet\test\Microsoft.Azure.ServiceBus.UnitTests\API\APIApprovals.cs:line 19
</details>

## Known limitations

Only works with .NET Framework. 
Since API is target independent, this should not be an issue.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@jtaubensee as promised. Please review.

**Comment by SeanFeldman** [comment]
@jtaubensee how come [appveyor](https://ci.appveyor.com/project/jtaubensee/azure-service-bus-dotnet/build/1.0.466/job/5pkk78ci5j27fowg/tests) didn't execute any of the tests?

**Comment by jtaubensee** [comment]
@SeanFeldman - Thanks for submitting this. I like the PR, however my only concern is all of the new dependencies:

* ApiApprover - MIT
* ApprovalTests - Apache 2.0
* ApprovalUtilities - Apache 2.0
* Mono.Cecil - MIT
* PublicApiGenerator - MIT

I assume no, but any way to trim these down? I ask because we have an internal review process for all external dependencies, and when we update them, we have to do it all over again.

> @jtaubensee how come appveyor didn't execute any of the tests?

So Appveyor will only run the "unit tests" (actually more like integration tests), when the PR comes from a branch in the repo (assumed to be trusted). When it doesn't, you could easily write a logging statement to write out the credentials used to provision the namespace.

I think that moving forward, it might be best to have multiple projects (1 for integration and 1 for unit).

**Comment by SeanFeldman** [comment]
> I assume no, but any way to trim these down?

Correct. Not something that is under my control.

> moving forward, it might be best to have multiple projects (1 for integration and 1 for unit).

👍

**Comment by SeanFeldman** [comment]
No more surprises in public API 🎉

**Pull request merged**
