### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by SimonCropp**
also fixes https://github.com/Azure/azure-service-bus-dotnet/issues/301

please cherry pick or merge as you want

### CODE REVIEW

**Comment by nemakam** [comment]
@SimonCropp, the build is failing after your check-in related to `directory.build.props`.
Could you take a look?
https://ci.appveyor.com/project/vinaysurya/azure-service-bus-dotnet/build/1.0.295/job/7bbotj54ygh5r0g1

**Comment by nemakam** [comment]
Reverted the signing changes in #313 
Related to https://github.com/Microsoft/msbuild/issues/2342

**Comment by SimonCropp** [comment]
@nemakam how exactly did i break it?

**Comment by nemakam** [comment]
Still haven't been able to get a green build since then.
Two things that I know of:
1. While refactoring common build properties to directory.build.props, `../../build/keyfile.snk` was referred to as `$(SolutionDir)/build/keyfile.snk`.
`dotnet test` command doesn't recognize this `$(SolutionDir)` variable and hence fails to import the key. Reverted the change.
2. One of the spelling correction changes updated one of the enums. Refer to https://github.com/Azure/azure-service-bus-dotnet/pull/313/commits/d6b4bd9640f563ca248c552892ca8197bd4616a0 . We use this `enum.ToString()` to send value to service which interprets it. But with this change, deferred messages functionality broke.

The build is still red. Trying to figure out what needs to be done.

**Comment by nemakam** [comment]
Active builds can be seen here: https://ci.appveyor.com/project/vinaysurya/azure-service-bus-dotnet/history

**Comment by SimonCropp** [comment]
so u can revert back to a relative instead of `$(SolutionDir)` but still use the common build props

> One of the spelling correction changes updated one of the enums. Refer to d6b4bd9 . We use this enum.ToString() to send value to service which interprets it. But with this change, deferred messages functionality broke.

doesnt this mean u have a spelling error in your service  api contract?

**Comment by nemakam** [comment]
> so u can revert back to a relative instead of $(SolutionDir) but still use the common build props

I haven't remove the `Directory.build.props` file. I just moved the signing part of it to its individual csproj files. Having the directory level property file dictate the relative path of this file for every csproj in that directory isn't a right approach. I may have another csproj later in a different directory structure which will break things.

>doesnt this mean u have a spelling error in your service api contract?

Correct!

**Comment by nemakam** [comment]
@SimonCropp, my computer decides to act weird suddenly. Could you run `ApproveAzureServiceBus()` test on your machine and send a PR with the changes to the `ApiApprovals.ApproveAzureServiceBus.approved.txt` file?

**Comment by SimonCropp** [comment]
targeting what branch?

**Comment by nemakam** [comment]
Could you target it to `authentican` branch I'm working on. Have all the build fixes in that branch.

**Comment by SimonCropp** [comment]
https://github.com/Azure/azure-service-bus-dotnet/pull/314

**Pull request merged**
