### PR TITLE
Making some internal classes and enums public

### PR DESCRIPTION
**Pull request by alexeyzimarev**
Making some internal classes and enums public.
https://github.com/Azure/azure-service-bus-dotnet/issues/335

### CODE REVIEW

**Comment by nemakam** [comment]
@alexeyzimarev , Thanks for the changes, but I don't think this is sufficient enough. You still cant use them even if you make these classes public since there is no way to provide a SAS token while creating a connection to service bus in this client.
This requires several things to be changed:
1. Instead of entities doing `var tokenProvider = TokenProvider.CreateSharedAccessSignatureTokenProvider()`, this needs to come from the `ServiceBusConnectionStringBuilder`.
1. In order to do that we will have to expose properties on `ServiceBusConnectionStringBuilder` which are required (mandatory or optional params) to create the token. E.g, `SharedAccessSingature` (SASToken), `TokenTimeToLive`, `TokenScope`.
1. Additionally we could also expose `TokenProvider` in connectionstring builder for people to plug in their own providers.
1. Given that we are already providing `TokenProvider` as a property, why should we still add properties like `SharedAccessSignature`? Since we support it natively and we would like to have `connectionStringBuilder.ToString()` return a connectionString which has `SharedAccessSignature=<>` in the string.
1. We will have to update all the entities to read `connectionStringBuilder.TokenProvider` instead of creating a new TokenProvider in the constructor.

**Comment by alexeyzimarev** [comment]
I think Clemens already made necessary changes in #338. I will wait for it to be merged and check if I can proceed. At least, some of the requested changes are made there.

**Comment by SeanFeldman** [comment]
Should this be closed @nemakam?

**Comment by vinaysurya** [comment]
Fixed with https://github.com/Azure/azure-service-bus-dotnet/pull/385

**Pull request closed without merging**
