### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
can u pick and choose parts of this PR u want. as i want to do some perf improvements next

**Comment by SimonCropp** [comment]
i think this also replaces https://github.com/Azure/azure-service-bus-dotnet/pull/307

**Comment by SimonCropp** [comment]
and regarding the `this.` changes. since you have explicitly commented out `dotnet_style_qualification_for...` i took that to mean you have no preference

https://github.com/Azure/azure-service-bus-dotnet/blob/dev/.editorconfig#L32-L35

**Comment by nemakam** [comment]
@SimonCropp
> can u pick and choose parts of this PR u want

If you don't mind, i'm going to revert the changes done in 
`2c5d9849b9bee2eafc66ecb35a1eb3aca2be6e9a` - remove redundant qualifiers and
`37df79167dd5660391e4299d51c64f62fa496440` - remove un-used methods.

The first one is to retain the `this` which we would like to continue to keep it consistent with our service side code and older client. There is no right/wrong here, but its about team's personal preference.
The second one removes couple of helper utility methods which may be useful later. They don't do any harm. 

Given that I'm having to cherry pick all the other commits individually to remove these two commits, I'll also exclude `var where evident` changes in favor of #307 since that came in earlier and is already checked in.

**Comment by nemakam** [comment]
And oops. Since it is a PR from your fork, don't think I can cherry pick commits as they are not in this repo yet. Could you cherry pick the remaining changes and send another PR?

**Comment by SimonCropp** [comment]
@nemakam 

> The second one removes couple of helper utility methods which may be useful later. They don't do any harm.

if you take the approach that this repo is "a bucket for code u might use in the future" then the signal to noise ratio will gradually get worse

**Comment by SimonCropp** [comment]
> And oops. Since it is a PR from your fork, don't think I can cherry pick commits as they are not in this repo yet. Could you cherry pick the remaining changes and send another PR?

you can u just need to pull the branch down locally first

**Comment by SimonCropp** [comment]
i will submit a new PR

**Comment by nemakam** [comment]
> you can u just need to pull the branch down locally first

Thanks. New things to learn everyday 👍

**Pull request closed without merging**
