### PR TITLE
Release 3.4.0

### PR DESCRIPTION
**Pull request by SeanFeldman**
### Bug fixes

- #653 MissingMemberException when receiving messages
- #648 NullReferenceException when accessing message.Size property
- #550 ISenderClient:SendAsync(IList<Message> messageList) throws null reference when messageList is empty
- #637 Management client doesn't return correct NamespaceInfo

### New features

- #644 Add support for configuring OperationTimeout in the connection string

### Enhancements

- #654 Update AMQP library to the latest (2.4.1)
- #668 Enable the use of a proxy when running in .NET Core

### CODE REVIEW

**Comment by nemakam** [comment]
@SeanFeldman , I've also merged #668 into dev. Lets take that as part of this release.

**Comment by SeanFeldman** [comment]
@nemakam done.

**Comment by SeanFeldman** [comment]
Will merge once build server is done.

**Comment by SeanFeldman** [comment]
Merged and `master` tagged.
Over to you @nemakam

**Comment by StefH** [comment]
Thanks for adding `Enable the use of a proxy when running in .NET Core` !

**Pull request merged**
