### PR TITLE
Replacing explicit types with var where evident

### PR DESCRIPTION
**Pull request by SeanFeldman**
## Description

This following list is used to make sure that common guidelines for a pull request are followed.

- **Read the [contribution guidelines](./CONTRIBUTING.md).** 
- Make title of the pull request clear and informative. 
- Link to appropriate [issue](https://github.com/Azure/azure-service-bus-dotnet/issues).
- Include test coverage for the changes.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
Related to #300

**Comment by nemakam** [comment]
(y)
Thanks

**Comment by nemakam** [comment]
@SeanFeldman, I am planning to revert this change for now in favor of #308. I hope that's okay.

**Comment by SeanFeldman** [comment]
Sure. Note that there were a few places that I didn't want to force a `var` for clarity of the type. As well as renaming variables to be more meaningful. But revert if you think merging #308 will give you too many conflicts to address.

**Pull request merged**
